version: '3.8'

services:
  test_voting_db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=voting_db_test
  
  test_runner:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - test_voting_db
    environment:
      # environment variables for the test runner
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_EXPIRE_MINUTES=${JWT_EXPIRE_MINUTES}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      
      # Test specific environment variables
      - RUNTIME=test
      - TEST_DB_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@test_voting_db:5432/voting_db_test

      # Python path for imports 
      - PYTHONPATH=/app
    volumes:
      - ./:/app:ro
      - ./test_reports:/app/test_reports # Volume for test reports
    command: >
      sh -c "
